# Array

## 亂數產生的 array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.randint(1,10,8) # 1-9, 取 8 個亂數

array([6, 8, 8, 3, 8, 2, 2, 2])

#### 取 0 到 1 間的亂數

例如取 20 個。

In [3]:
np.random.rand(20)

array([0.45929941, 0.78444255, 0.7423792 , 0.15980149, 0.16308819,
       0.84097525, 0.66187958, 0.13924994, 0.33597205, 0.75105009,
       0.26245267, 0.10634413, 0.84191959, 0.85096332, 0.76405468,
       0.48106202, 0.2470663 , 0.12234318, 0.88874291, 0.56819714])

#### 由平均 0, 標準差 1 的分布中取 20 個數

In [4]:
np.random.randn(20)

array([ 0.89973057,  0.32926518,  0.23830942, -0.35120953,  0.76965845,
        1.00953828, -1.30555213,  0.20886353,  1.63637604,  2.23484151,
       -0.02654486, -1.70977661,  0.49665303,  0.30221773,  0.86934258,
        1.00530287, -0.63192946, -1.59274056,  0.59808084,  1.0985474 ])

#### 試取 100 個, 算平均、標準差

In [5]:
g = np.random.randn(100)

In [6]:
g.mean()

0.0971535058847299

In [7]:
g.std()

0.825995760076057

In [8]:
g

array([ 0.27996245,  0.99358202, -0.7358324 ,  1.30607739, -0.19469608,
       -0.66275912, -0.42772372, -0.00552971,  1.22395469,  0.2712324 ,
       -1.35781769, -0.17297214, -0.19538359, -0.91604915,  0.56341519,
       -0.17983487, -0.70230529, -0.03346482, -0.63643852,  0.88578695,
        0.07966513, -0.15690191, -0.38720311,  0.11575186,  0.27649155,
        0.6905428 , -0.22523959,  0.82666261, -0.206363  , -0.26826201,
        1.14706911,  0.10363965,  0.82045029,  0.32262787,  0.97590236,
       -0.71364479, -0.0937099 , -0.66856103,  0.93500793, -0.20072619,
        2.49318564,  0.51553309, -0.2020984 , -0.27348444,  0.35932   ,
        0.22320147, -1.67345844, -0.58841325,  1.0391225 , -1.05517988,
       -0.23712746, -0.85437713,  0.86417309, -1.7816715 ,  0.15262367,
        1.12457451, -0.92636199, -0.78476635,  0.75230425,  0.52937304,
        0.52651154,  0.24276331, -0.35689152,  1.57317625, -0.22535294,
        0.33563786,  2.41540555,  0.60069923,  0.36850574,  0.70

#### 不同的平均值和標準差

比如我們想要平均值變成 70, 標準差 10 怎麼做呢?

In [9]:
g2 = g*10 + 70

In [10]:
g2

array([72.79962448, 79.93582023, 62.64167602, 83.06077392, 68.05303923,
       63.37240879, 65.72276277, 69.94470293, 82.23954694, 72.71232404,
       56.4218231 , 68.27027857, 68.04616411, 60.83950846, 75.63415186,
       68.20165125, 62.97694707, 69.66535175, 63.63561481, 78.85786948,
       70.79665128, 68.43098093, 66.12796885, 71.15751861, 72.7649155 ,
       76.90542803, 67.74760408, 78.26662605, 67.93637004, 67.31737994,
       81.47069106, 71.03639652, 78.20450292, 73.22627873, 79.75902364,
       62.86355206, 69.06290099, 63.3143897 , 79.35007933, 67.99273808,
       94.93185641, 75.15533092, 67.97901604, 67.26515564, 73.59320001,
       72.23201467, 53.26541558, 64.11586754, 80.39122497, 59.44820116,
       67.62872541, 61.45622869, 78.64173087, 52.18328504, 71.52623665,
       81.2457451 , 60.73638011, 62.15233651, 77.52304251, 75.29373038,
       75.26511541, 72.42763307, 66.4310848 , 85.73176246, 67.74647058,
       73.35637864, 94.15405547, 76.00699231, 73.68505737, 77.07

#### [練習] 將 Temperature_Taipei 中的所有溫度都轉成華氏
Temperature_Taipei = [22, 24, 19, 19, 30, 21, 25]

公式： Fahrenheit=Celsius×(9/5)+32

In [11]:
Temperature_array = np.array([22, 24, 19, 19, 30, 21, 25])

Temperature_array_Fahrenheit = (Temperature_array) * ( 9 / 5 ) + 32
print(Temperature_array_Fahrenheit)

[71.6 75.2 66.2 66.2 86.  69.8 77. ]


#### [練習] 利用array, 寫出一張九九乘法表

In [12]:
multiplication = np.empty( (9 , 9) ) 

for i in range(1,10): 
    for j in range(1,10): 
        multiplication[(i-1),(j-1)]= i*j
print(multiplication)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]
